name: Build Flutter Web and Deploy to /docs (via Token)

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # disable default token

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'

      - name: Enable web support
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --base-href="/LM-Shipment/"  # 🔥 Important for GitHub Pages

      - name: Clone dev branch and clean docs/
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Clone the repo with token
          git clone --branch dev https://x-access-token:${TOKEN}@github.com/${{ github.repository }} temp

          cd temp
          rm -rf docs
          mkdir docs
          cp -r ../build/web/* docs/

          git add docs
          git commit -m "Clean and redeploy Flutter web to /docs" || echo "No changes to commit"
          git push origin dev
