name: Build Flutter Web to /docs (Flutter 1.20.0 / Dart 2.9)

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Required for pushing

      - name: Setup Flutter 2.10.5 (Dart >=2.12)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'

      - name: Enable web support
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web

      - name: Copy build to /docs
        run: |
          rm -rf docs
          mkdir docs
          cp -r build/web/* docs/

      - name: Commit and push changes to develop branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Update /docs with Flutter web build" || echo "No changes to commit"
          git push origin develop
