name: Build Flutter Web and Force-Push to /docs on dev

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'

      - name: Enable web support
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web

      - name: Push /docs to dev branch (clean replace)
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}

          # Fetch latest dev branch
          git fetch origin dev

          # Create temp worktree for clean push
          git worktree add /tmp/dev-worktree origin/dev

          # Clean old docs and copy new ones
          rm -rf /tmp/dev-worktree/docs
          mkdir /tmp/dev-worktree/docs
          cp -r build/web/* /tmp/dev-worktree/docs/

          # Commit and push changes to dev
          cd /tmp/dev-worktree
          git add docs
          git commit -m "Deploy fresh Flutter web build to /docs" || echo "No changes to commit"
          git push origin HEAD:dev

          # Cleanup
          cd $GITHUB_WORKSPACE
          git worktree remove /tmp/dev-worktree --force
