name: Build Flutter Web and Push /docs to dev

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'

      - name: Enable web support
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web

      - name: Prepare /docs folder
        run: |
          rm -rf docs
          mkdir docs
          cp -r build/web/* docs/

      - name: Push /docs to dev branch
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          # Create a temp worktree for the dev branch
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          
          git fetch origin dev
          git worktree add /tmp/dev-worktree dev

          # Copy docs to dev worktree and push
          rm -rf /tmp/dev-worktree/docs
          cp -r docs /tmp/dev-worktree/

          cd /tmp/dev-worktree
          git add docs
          git commit -m "Update Flutter web build in /docs" || echo "No changes to commit"
          git push origin dev

          # Clean up
          cd $GITHUB_WORKSPACE
          git worktree remove /tmp/dev-worktree
