name: Build Flutter Web to /docs

on:
  push:
    branches:
      - dev  # Trigger on push to dev branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter with Dart 3.0.0 (via Flutter 3.10.0)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Copy build to /docs
        run: |
          rm -rf docs
          mkdir docs
          cp -r build/web/* docs/

      - name: Commit and push changes to /docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Deploy Flutter web build to /docs" || echo "No changes to commit"
          git push origin dev
